// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Component: typeof import('./src/components/Component/index.vue')['default']
    ComponentWarp: typeof import('./src/components/ComponentWarp/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPageHeader: typeof import('element-plus/es')['ElPageHeader']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    Header: typeof import('./src/components/Header/index.vue')['default']
    'Header copy': typeof import('./src/components/Header copy/index.vue')['default']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    QueryTable: typeof import('./src/components/BusinessComponent/QueryTable/index.vue')['default']
    RenderElement: typeof import('./src/components/BusinessComponent/QueryTable/components/RenderElement/index.vue')['default']
    Test: typeof import('./src/components/BusinessComponent/QueryTable/components/test/index.vue')['default']
    Vnode: typeof import('./src/components/BusinessComponent/QueryTable/components/Vnode.vue')['default']
    VNode: typeof import('./src/components/BusinessComponent/QueryTable/components/VNode.ts')['default']
  }
}

export { }
