// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BaseLayout: typeof import('./src/components/BaseLayout/index.vue')['default']
    ChilrenComponent: typeof import('./src/components/ChilrenComponent/index.vue')['default']
    ComponentWarp: typeof import('./src/components/ComponentWarp/index.vue')['default']
    Content: typeof import('./src/components/Header/components/content.vue')['default']
    Header: typeof import('./src/components/Header/index.vue')['default']
    Logo: typeof import('./src/components/Header/components/logo.vue')['default']
    MultiTab: typeof import('./src/components/MultiTab/index.vue')['default']
    QueryTable: typeof import('./src/components/BusinessComponent/QueryTable/index.vue')['default']
  }
}

export { }
